"""
MockMind Fallback Question Bank Seeder
Run: python scripts/seed_fallback.py

MongoDB me 500+ questions daalega:
- question_bank: 495 technical questions (9 roles x 55 each)
- coding_problems: 50 coding problems (easy/medium/hard)
- hr_questions: 100 HR/behavioral questions
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from models import question_bank_col, coding_problems_col, hr_questions_col

# ══════════════════════════════════════════════════════════════
# SECTION 1: TECHNICAL QUESTIONS (question_bank)
# 9 roles x 55 questions each = 495 total
# Difficulty distribution per role: 20 easy, 20 medium, 15 hard
# ══════════════════════════════════════════════════════════════

FRONTEND_QUESTIONS = {
    "easy": [
        "What is the difference between HTML and HTML5?",
        "What are semantic tags in HTML? Give examples.",
        "Explain the box model in CSS.",
        "What is the difference between display: none and visibility: hidden?",
        "What are CSS Flexbox and CSS Grid? When do you use each?",
        "What is responsive design? How do you achieve it?",
        "What is the difference between class and id selectors in CSS?",
        "Explain event bubbling and event capturing in JavaScript.",
        "What is the difference between var, let, and const in JavaScript?",
        "What is hoisting in JavaScript?",
        "What is the DOM in web development?",
        "What are cookies, localStorage, and sessionStorage?",
        "What is CORS and why does it exist?",
        "What is the difference between GET and POST requests?",
        "What is JSON and why is it used in web development?",
        "What is a CDN and why do we use it?",
        "What is the difference between inline, internal, and external CSS?",
        "What are CSS preprocessors? Name a few.",
        "What is the purpose of the meta viewport tag?",
        "What is the difference between == and === in JavaScript?",
    ],
    "medium": [
        "What is the Virtual DOM in React and how does it work?",
        "Explain the React component lifecycle methods.",
        "What is prop drilling and how can you avoid it?",
        "What are React Hooks? Explain useState and useEffect.",
        "What is the difference between controlled and uncontrolled components?",
        "Explain event delegation and why it is useful.",
        "What is closure in JavaScript? Give a practical example.",
        "What is the difference between map, filter, and reduce?",
        "How does the event loop work in JavaScript?",
        "What is the difference between Promise and callback?",
        "What is async/await and how does it differ from Promises?",
        "What are Web Workers? When would you use them?",
        "Explain CSS specificity and how it determines which styles apply.",
        "What is the difference between position: absolute, relative, fixed, and sticky?",
        "What is the box-sizing: border-box property and why is it useful?",
        "How does CSS animation work? Explain keyframes.",
        "What is the difference between SSR, SSG, and ISR?",
        "What is lazy loading and how do you implement it in React?",
        "What are React Context and when should you use it?",
        "What is the purpose of React.memo and useMemo?",
    ],
    "hard": [
        "Explain the React Fiber architecture and its benefits.",
        "What are Server Components in React 18? How do they differ from Client Components?",
        "How does code splitting work with React.lazy and Suspense?",
        "Explain the concept of reconciliation in React.",
        "What is the difference between micro frontends and monolithic frontends?",
        "How do you implement infinite scrolling with proper caching and deduplication?",
        "Explain the Critical Rendering Path and how to optimize it.",
        "What is the Shadow DOM and how is it used in Web Components?",
        "How does requestAnimationFrame work compared to setTimeout for animations?",
        "Explain the difference between CORS preflight and simple requests.",
        "What are Progressive Web Apps and how do Service Workers enable them?",
        "How do you handle form validation in React without a library?",
        "Explain the difference between localStorage, sessionStorage, and IndexedDB.",
        "What is the performance impact of reflows and repaints? How do you minimize them?",
        "How do you implement optimistic UI updates while handling server validation failures?",
    ],
}

BACKEND_QUESTIONS = {
    "easy": [
        "What is a REST API? What are its main principles?",
        "What is the difference between SQL and NoSQL databases?",
        "What is HTTP? Explain the difference between HTTP and HTTPS.",
        "What are HTTP status codes? Explain 200, 301, 404, and 500.",
        "What is middleware in a web framework?",
        "What is authentication vs authorization?",
        "What is a database index and why is it important?",
        "What is the difference between a stack and a queue?",
        "What is a hash table and how does it work?",
        "Explain CRUD operations in a database.",
        "What is connection pooling and why is it used?",
        "What is the difference between TCP and UDP?",
        "What is a socket and when would you use one?",
        "What is serialization and deserialization?",
        "What is the difference between a process and a thread?",
        "What is a RESTful web service?",
        "What is GraphQL and how does it differ from REST?",
        "What is a load balancer and why do we need it?",
        "What is caching? Name a few caching strategies.",
        "What is the difference between horizontal and vertical scaling?",
    ],
    "medium": [
        "Explain the CAP theorem with real-world examples.",
        "What is database sharding? What problems does it solve?",
        "How does JWT authentication work step by step?",
        "What is idempotency in REST APIs? Why is it important?",
        "Explain ACID properties with a banking example.",
        "What is the difference between message queues like RabbitMQ and Kafka?",
        "How do you implement rate limiting? Compare token bucket and sliding window.",
        "What is database connection pooling? How does it improve performance?",
        "Explain the difference between optimistic and pessimistic locking.",
        "What is the saga pattern for distributed transactions?",
        "How does connection keep-alive work in HTTP/1.1 vs HTTP/2?",
        "What is a reverse proxy? When would you use one?",
        "Explain the N+1 query problem in ORMs.",
        "What is the difference between a monolith and microservices architecture?",
        "How do you implement API versioning?",
        "What is database normalization? Explain 1NF, 2NF, and 3NF.",
        "What are WebSockets and how do they differ from HTTP polling?",
        "How do you handle graceful shutdown in a backend service?",
        "Explain caching invalidation strategies: write-through, write-behind, write-around.",
        "What is a circuit breaker pattern? When would you use it?",
    ],
    "hard": [
        "Design a URL shortener like bit.ly that handles billions of URLs.",
        "How would you design a real-time chat application at scale?",
        "Explain the two-phase commit protocol and its limitations.",
        "How do you implement distributed caching with cache coherence?",
        "Design a notification system that supports email, SMS, and push notifications.",
        "How would you handle 1 million concurrent WebSocket connections?",
        "Explain event sourcing and CQRS pattern. When would you use each?",
        "How do you implement zero-downtime database migrations?",
        "Design a rate limiter that works across multiple server instances.",
        "How would you implement a distributed task scheduler?",
        "Explain the difference between consistency, availability, and partition tolerance in practice.",
        "How do you handle database failover in a production environment?",
        "Design a file upload system that handles large files with resumable uploads.",
        "How would you implement a real-time leaderboard for millions of users?",
        "Explain how you would debug a production issue with high latency.",
    ],
}

FULLSTACK_QUESTIONS = {
    "easy": [
        "What is the difference between frontend and backend development?",
        "What is a full stack developer? What technologies do they need?",
        "Explain the request-response cycle in a web application.",
        "What is the difference between client-side and server-side rendering?",
        "What is a REST API and how does a frontend communicate with it?",
        "What is JSON and why is it used for API communication?",
        "What is the difference between a web server and an application server?",
        "What is a database driver and why is it needed?",
        "What is the difference between a framework and a library?",
        "What is version control and why do we use Git?",
        "What is the difference between npm and npx?",
        "What is a build tool? Name a few popular ones.",
        "What is the difference between development and production environments?",
        "What is environment variable management and why is it important?",
        "What is CORS and how do you handle it in a full stack app?",
    ],
    "medium": [
        "How would you design a real-time chat application across the full stack?",
        "Explain the difference between REST and GraphQL. When would you choose each?",
        "How do you handle authentication across a frontend SPA and backend API?",
        "What is the BFF (Backend for Frontend) pattern?",
        "How would you implement search autocomplete across the full stack?",
        "Explain the difference between polling, long-polling, SSE, and WebSockets.",
        "How do you implement file uploads from frontend to backend?",
        "What is the Strangler Fig pattern for migrating a monolith to microservices?",
        "How do you manage state across microservices in an e-commerce application?",
        "How would you implement RBAC across frontend routes and backend APIs?",
        "Explain how you would debug a slow page load in production.",
        "How do you implement dark mode across a full stack application?",
        "What is the difference between serverless and containerized deployments?",
        "How do you handle error boundaries in React and error handling in Express?",
        "What is database seeding and migration? How do you manage schema changes?",
    ],
    "hard": [
        "Design a complete e-commerce system from scratch covering all layers.",
        "How would you implement a real-time collaborative editing tool like Google Docs?",
        "Explain how you would design a CI/CD pipeline for a full stack application.",
        "How do you implement distributed tracing across frontend and backend?",
        "Design a multi-tenant SaaS application with proper data isolation.",
        "How would you implement a feature flag system across the entire stack?",
        "Explain how you would handle data consistency in a microservices architecture.",
        "How do you implement A/B testing across frontend and backend?",
        "Design a notification system that handles millions of users.",
        "How would you implement a real-time dashboard with live metrics?",
        "Explain how you would migrate a monolithic database to microservices databases.",
        "How do you implement internationalization (i18n) across the full stack?",
        "Design a payment processing system with proper error handling and rollback.",
        "How would you implement a content management system with a headless architecture?",
        "Explain how you would handle cross-cutting concerns like logging and monitoring.",
    ],
}

ML_QUESTIONS = {
    "easy": [
        "What is machine learning? Name the main types of ML.",
        "What is the difference between supervised and unsupervised learning?",
        "What is a training set vs a test set?",
        "What is overfitting and how do you prevent it?",
        "What is a decision tree? How does it make predictions?",
        "What is linear regression? When would you use it?",
        "What is classification vs regression?",
        "What is a feature in machine learning?",
        "What is label encoding vs one-hot encoding?",
        "What is the difference between parametric and non-parametric models?",
        "What is cross-validation and why is it important?",
        "What is a confusion matrix?",
        "What is precision and recall? When would you optimize for each?",
        "What is the bias-variance tradeoff?",
        "What is feature scaling and why is it necessary?",
    ],
    "medium": [
        "Explain the difference between L1 and L2 regularization.",
        "How does a Random Forest handle overfitting compared to a single Decision Tree?",
        "What is the vanishing gradient problem? How do LSTM and ResNet address it?",
        "Explain the attention mechanism in Transformers.",
        "What is transfer learning? How would you fine-tune a pre-trained BERT model?",
        "How does gradient boosting work? Compare XGBoost and LightGBM.",
        "What is data leakage? Give examples of how it happens.",
        "Explain the difference between batch normalization and layer normalization.",
        "What is the curse of dimensionality? How does PCA help?",
        "How do you handle imbalanced datasets? Compare oversampling and SMOTE.",
        "What is a learning rate? How does it affect model training?",
        "Explain the difference between generative and discriminative models.",
        "What is feature importance? How do you compute it?",
        "What is ensemble learning? Explain bagging and boosting.",
        "How do you handle missing data in a machine learning pipeline?",
    ],
    "hard": [
        "Explain the architecture of a Transformer model in detail.",
        "How would you design an end-to-end ML pipeline for production?",
        "What is reinforcement learning? Explain Q-learning and policy gradients.",
        "How do you detect and handle concept drift in production models?",
        "Explain how GANs (Generative Adversarial Networks) work.",
        "What is few-shot learning? How does it differ from zero-shot learning?",
        "How would you implement model interpretability using SHAP values?",
        "Explain the difference between model serving strategies: batch vs real-time.",
        "What is neural architecture search (NAS)?",
        "How do you handle multi-modal data in machine learning?",
        "Explain how diffusion models generate images.",
        "What is contrastive learning? How is it used in self-supervised learning?",
        "How would you design a recommendation system for millions of users?",
        "Explain the attention mechanism in detail with mathematical formulation.",
        "What is quantization and pruning in model optimization?",
    ],
}

DATASCIENCE_QUESTIONS = {
    "easy": [
        "What is data science? How is it different from statistics?",
        "What is Exploratory Data Analysis (EDA)?",
        "What is a data pipeline?",
        "What is the difference between population and sample?",
        "What is a random variable?",
        "What is the normal distribution and why is it important?",
        "What is correlation vs causation?",
        "What is a histogram vs a bar chart?",
        "What is outlier detection? Why is it important?",
        "What is data cleaning? What are common cleaning steps?",
        "What is the difference between mean, median, and mode?",
        "What is standard deviation and variance?",
        "What is a scatter plot and what does it show?",
        "What is data wrangling?",
        "What is the difference between structured and unstructured data?",
    ],
    "medium": [
        "Explain the p-value in hypothesis testing.",
        "What is Simpson's Paradox? Give a real-world example.",
        "How do you handle multicollinearity in regression?",
        "Explain the Central Limit Theorem and its importance.",
        "What is the difference between ANOVA and t-test?",
        "How do you design an A/B test from scratch?",
        "Explain the difference between exploratory and confirmatory analysis.",
        "What is survival analysis? When would you use it?",
        "How do you detect and handle outliers? Compare Z-score and IQR.",
        "What is a funnel analysis? How do you identify drop-off points?",
        "How do you handle imbalanced classes in classification?",
        "Explain time series decomposition: trend, seasonality, residual.",
        "What is the difference between parametric and non-parametric tests?",
        "How do you build a recommendation system? Compare approaches.",
        "What is Bayesian inference? How does it differ from frequentist approach?",
    ],
    "hard": [
        "How would you design a real-time analytics pipeline for billions of events?",
        "Explain causal inference methods: difference-in-differences, instrumental variables.",
        "How do you handle missing data in time series analysis?",
        "What is the difference between ARIMA, SARIMA, and Prophet for forecasting?",
        "How would you implement anomaly detection at scale?",
        "Explain the concept of statistical power and sample size calculation.",
        "How do you build a data lake vs a data warehouse? When would you choose each?",
        "What is feature engineering? How do you automate it?",
        "How would you handle data drift in a production ML system?",
        "Explain the difference between batch processing and stream processing.",
        "How do you implement A/B testing with multiple variants?",
        "What is the bootstrap method? How is it used for confidence intervals?",
        "How would you design a data governance framework?",
        "Explain hierarchical clustering and when to use it over k-means.",
        "How do you handle high-cardinality categorical features?",
    ],
}

ANALYST_QUESTIONS = {
    "easy": [
        "What is a SQL JOIN? Explain INNER, LEFT, and RIGHT JOIN.",
        "What is the difference between DELETE, TRUNCATE, and DROP?",
        "What is a pivot table and when would you use one?",
        "What is a VLOOKUP and how does it work?",
        "What is conditional formatting in Excel?",
        "What is a CSV file?",
        "What is the difference between a bar chart and a pie chart?",
        "What is a KPI (Key Performance Indicator)?",
        "What is data validation in Excel?",
        "What is a calculated field?",
        "What is the difference between a formula and a function in Excel?",
        "What is filtering and sorting in spreadsheets?",
        "What is a data dictionary?",
        "What is a primary key in a database?",
        "What is a database view?",
    ],
    "medium": [
        "Write a SQL query to find the top 3 customers by revenue in each region.",
        "What are window functions in SQL? Explain ROW_NUMBER and RANK.",
        "How do you create a cohort analysis in SQL or Excel?",
        "What is the difference between descriptive, diagnostic, predictive, and prescriptive analytics?",
        "How would you build a dashboard in Tableau or Power BI?",
        "How do you calculate moving averages? Compare SMA and EMA.",
        "Explain normalization vs standardization. When do you apply each?",
        "How do you handle missing values in a dataset?",
        "What is the difference between a bar chart, histogram, and box plot?",
        "How do you calculate year-over-year growth in SQL?",
        "What is statistical significance vs practical significance?",
        "How do you handle dirty data in a dataset?",
        "What is a data warehouse vs a data lake?",
        "How do you create an interactive dashboard?",
        "What is ETL and why is it important?",
    ],
    "hard": [
        "How would you design a data analytics platform for a large e-commerce company?",
        "Explain how you would perform root cause analysis for a sudden drop in revenue.",
        "How do you build a real-time analytics dashboard?",
        "What is the difference between OLTP and OLAP systems?",
        "How would you optimize a slow-running SQL query with millions of rows?",
        "Explain how you would design a data quality framework.",
        "How do you handle data privacy regulations like GDPR in analytics?",
        "What is the difference between data governance and data management?",
        "How would you implement data lineage tracking?",
        "Explain how you would build an automated reporting system.",
        "How do you handle multi-source data integration?",
        "What is a data mesh architecture?",
        "How would you design metrics and dimensions for a star schema?",
        "Explain how you would validate data accuracy across multiple sources.",
        "How do you build a self-service analytics platform?",
    ],
}

PYTHON_QUESTIONS = {
    "easy": [
        "What is Python? What are its main advantages?",
        "What are the differences between a list and a tuple?",
        "What is a dictionary in Python?",
        "What is the difference between a function and a method?",
        "What is a module in Python?",
        "What is pip and how is it used?",
        "What is the difference between deep copy and shallow copy?",
        "What are *args and **kwargs?",
        "What is a lambda function?",
        "What is list comprehension?",
        "What is the difference between == and is?",
        "What is a string? How do you slice strings in Python?",
        "What is a set? How is it different from a list?",
        "What is indentation and why is it important in Python?",
        "What is the pass statement?",
    ],
    "medium": [
        "Explain Python's GIL (Global Interpreter Lock). How does it affect threading?",
        "What is the difference between a generator and an iterator?",
        "How do decorators work in Python?",
        "What are metaclasses? When would you use __init_subclass__?",
        "How does Python's memory management work?",
        "What is the difference between *args, **kwargs, and keyword-only arguments?",
        "Explain context managers. How do you write a custom one?",
        "What is the difference between asyncio and multiprocessing?",
        "How do you profile a Python application for memory leaks?",
        "What are Python dataclasses? How do they differ from regular classes?",
        "How does Python's import system work?",
        "What is monkey patching and why is it dangerous?",
        "Explain the difference between map, filter, and reduce.",
        "How do you handle circular imports?",
        "What is the difference between __str__ and __repr__?",
    ],
    "hard": [
        "How would you implement a custom metaclass with __new__ and __init_subclass__?",
        "Explain the descriptor protocol and how properties work internally.",
        "How do you implement a context manager that handles multiple resources?",
        "What are Python internals? How does CPython compile and execute code?",
        "How would you implement a thread-safe singleton in Python?",
        "Explain the difference between coroutines, tasks, and futures in asyncio.",
        "How do you implement a custom exception hierarchy with chaining?",
        "What is the difference between __slots__ and regular attributes?",
        "How would you implement a LRU cache from scratch?",
        "Explain how Python's garbage collector handles circular references.",
        "How do you implement a custom iterator with __iter__ and __next__?",
        "What is the difference between abstract base classes and protocols?",
        "How would you implement a plugin system using importlib?",
        "Explain how Python handles type hints and runtime type checking.",
        "How do you implement a lazy loading mechanism for expensive computations?",
    ],
}

UIUX_QUESTIONS = {
    "easy": [
        "What is UX design vs UI design?",
        "What is a wireframe?",
        "What is a mockup vs a prototype?",
        "What is the difference between usability and accessibility?",
        "What is a user persona?",
        "What is a user journey map?",
        "What is white space in design?",
        "What is the difference between serif and sans-serif fonts?",
        "What is color theory?",
        "What is a call-to-action (CTA)?",
        "What is responsive design?",
        "What is a design system?",
        "What is A/B testing in design?",
        "What is the difference between UX research and UX design?",
        "What is a mood board?",
    ],
    "medium": [
        "Explain Nielsen's 10 usability heuristics.",
        "What is information architecture? How do you organize content?",
        "How do you approach designing for accessibility (WCAG)?",
        "What is the difference between usability testing and heuristic evaluation?",
        "Explain atomic design methodology.",
        "What is Fitts's Law? How does it influence button design?",
        "Explain Gestalt principles of visual perception.",
        "How do you handle design handoff to developers?",
        "What is a design audit? How do you conduct one?",
        "What is the difference between user-centered design and human-centered design?",
        "How do you conduct user testing? Compare moderated vs unmoderated.",
        "What is microcopy and how does it affect user experience?",
        "Explain the double diamond design process.",
        "What is the difference between responsive, adaptive, and fluid design?",
        "How do you handle design debt?",
    ],
    "hard": [
        "How would you design a design system for a large organization?",
        "Explain how you would conduct a comprehensive UX audit.",
        "How do you measure ROI of UX design improvements?",
        "What is the difference between inclusive design and universal design?",
        "How would you design for users with cognitive disabilities?",
        "Explain how you would approach designing a complex data visualization.",
        "How do you balance business goals with user needs in design?",
        "What is the role of emotion in design? How do you design for delight?",
        "How would you design a cross-platform experience (web, mobile, desktop)?",
        "Explain how you would conduct competitive analysis for design.",
        "How do you handle stakeholder disagreements in design decisions?",
        "What is the difference between UX writing and content design?",
        "How would you design an onboarding flow for a complex SaaS product?",
        "Explain how you would approach designing for emerging markets.",
        "How do you maintain design consistency across a large product team?",
    ],
}

DEVOPS_QUESTIONS = {
    "easy": [
        "What is DevOps? What are its core principles?",
        "What is the difference between a Docker image and a container?",
        "What is version control and why do we use Git?",
        "What is CI/CD?",
        "What is a YAML file?",
        "What is the difference between a virtual machine and a container?",
        "What is a shell script?",
        "What is the difference between a process and a daemon?",
        "What is an environment variable?",
        "What is a package manager?",
        "What is Linux? Why is it preferred for servers?",
        "What is SSH and how does it work?",
        "What is a firewall?",
        "What is DNS and how does it work?",
        "What is the difference between TCP and UDP?",
    ],
    "medium": [
        "How does Kubernetes scheduling work? Explain pods, deployments, and services.",
        "What is Infrastructure as Code? Compare Terraform and CloudFormation.",
        "Explain the GitOps workflow. How does ArgoCD automate deployments?",
        "What is a service mesh? Explain Istio or Linkerd.",
        "How do you set up a CI/CD pipeline from scratch?",
        "Compare blue-green, canary, and rolling deployments.",
        "What is observability? Compare logs, metrics, and traces.",
        "How do you handle secrets in Kubernetes?",
        "Explain networking in Kubernetes. How do services communicate?",
        "What is the difference between a StatefulSet and a Deployment?",
        "How do you implement auto-scaling? Compare HPA, VPA, and cluster autoscaler.",
        "How do Prometheus and Grafana work together for monitoring?",
        "What is the blast radius of a failed deployment?",
        "How do you handle disaster recovery? Explain RTO and RPO.",
        "What is the difference between a sidecar pattern and an ambassador pattern?",
    ],
    "hard": [
        "How would you design a zero-downtime deployment pipeline?",
        "Explain how you would implement multi-cluster Kubernetes federation.",
        "How do you handle stateful workloads in Kubernetes?",
        "What is the difference between service mesh and API gateway?",
        "How would you implement chaos engineering in production?",
        "Explain how you would design a multi-region high availability architecture.",
        "How do you handle compliance and security in a CI/CD pipeline?",
        "What is the difference between GitOps and traditional CD?",
        "How would you implement infrastructure testing (infratest)?",
        "Explain how you would handle a production incident post-mortem.",
        "How do you implement cost optimization for cloud infrastructure?",
        "What is the difference between eBPF and iptables for networking?",
        "How would you design a platform engineering team structure?",
        "Explain how you would implement supply chain security for containers.",
        "How do you handle configuration drift across environments?",
    ],
}

ALL_TECH_QUESTIONS = {
    "frontend developer": FRONTEND_QUESTIONS,
    "backend developer": BACKEND_QUESTIONS,
    "full stack developer": FULLSTACK_QUESTIONS,
    "machine learning": ML_QUESTIONS,
    "data science": DATASCIENCE_QUESTIONS,
    "data analyst": ANALYST_QUESTIONS,
    "python developer": PYTHON_QUESTIONS,
    "ui/ux designer": UIUX_QUESTIONS,
    "devops engineer": DEVOPS_QUESTIONS,
}

def build_question_bank_docs():
    """question_bank collection ke liye documents banao."""
    docs = []
    for role, difficulties in ALL_TECH_QUESTIONS.items():
        for difficulty, questions in difficulties.items():
            for q in questions:
                docs.append({
                    "role": role,
                    "type": "technical",
                    "difficulty": difficulty,
                    "question": q,
                    "asked_count": 0,
                    "avg_score": 0.0,
                    "total_score_sum": 0.0,
                    "times_scored": 0,
                })
    return docs


# ══════════════════════════════════════════════════════════════
# SECTION 2: CODING PROBLEMS (coding_problems)
# 50 problems: 15 easy, 20 medium, 15 hard
# ══════════════════════════════════════════════════════════════

CODING_PROBLEMS = [
    # ── EASY (15) ──
    {"title": "Two Sum", "difficulty": "easy", "topic": "arrays",
     "description": "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
     "function_signature": {"python": "def solution(nums, target):", "java": "public int[] solution(int[] nums, int target)", "cpp": "vector<int> solution(vector<int>& nums, int target)", "c": "int* solution(int* nums, int n, int target, int* returnSize)"},
     "examples": [{"input": "[2,7,11,15]\n9", "output": "[0,1]", "explanation": "nums[0]+nums[1]=9"}],
     "constraints": ["2 <= nums.length <= 10^4", "Only one valid answer exists"],
     "starter_code": {"python": "def solution(nums, target):\n    pass", "javascript": "function solution(nums, target) {}", "java": "class Solution {\n    public int[] solution(int[] nums, int target) {\n        return new int[]{};\n    }\n}", "cpp": "vector<int> solution(vector<int>& nums, int target) {\n    return {};\n}", "c": "int* solution(int* nums, int n, int target, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[2,7,11,15]\n9", "expected": "[0,1]"}, {"input": "[3,2,4]\n6", "expected": "[1,2]"}, {"input": "[3,3]\n6", "expected": "[0,1]"}],
     "hints": ["Use a HashMap to store elements you have seen.", "For each element, check if its complement exists in the map."]},

    {"title": "Reverse String", "difficulty": "easy", "topic": "strings",
     "description": "Write a function that reverses a string. Return the reversed string.",
     "function_signature": {"python": "def solution(s):", "java": "public String solution(String s)", "cpp": "string solution(string s)", "c": "char* solution(char* s)"},
     "examples": [{"input": "hello", "output": "olleh", "explanation": "Reverse characters"}],
     "constraints": ["1 <= s.length <= 10^5"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public String solution(String s) {\n        return \"\";\n    }\n}", "cpp": "string solution(string s) {\n    return \"\";\n}", "c": "char* solution(char* s) {\n    return s;\n}"},
     "test_cases": [{"input": "hello", "expected": "olleh"}, {"input": "Hannah", "expected": "hannaH"}, {"input": "a", "expected": "a"}],
     "hints": ["Use two pointers from both ends.", "Swap characters and move towards center."]},

    {"title": "Valid Parentheses", "difficulty": "easy", "topic": "strings",
     "description": "Given a string of brackets, determine if the input string is valid.",
     "function_signature": {"python": "def solution(s):", "java": "public boolean solution(String s)", "cpp": "bool solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "()[]{}", "output": "true", "explanation": "All brackets properly closed"}],
     "constraints": ["1 <= s.length <= 10^4"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public boolean solution(String s) {\n        return false;\n    }\n}", "cpp": "bool solution(string s) {\n    return false;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": "()", "expected": "true"}, {"input": "()[]{}", "expected": "true"}, {"input": "(]", "expected": "false"}],
     "hints": ["Use a stack data structure.", "Push open brackets, pop when matching close bracket found."]},

    {"title": "Palindrome Check", "difficulty": "easy", "topic": "strings",
     "description": "Given a string, determine if it is a palindrome considering only alphanumeric characters.",
     "function_signature": {"python": "def solution(s):", "java": "public boolean solution(String s)", "cpp": "bool solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "A man, a plan, a canal: Panama", "output": "true", "explanation": "Reads same forwards and backwards"}],
     "constraints": ["1 <= s.length <= 2*10^5"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public boolean solution(String s) {\n        return false;\n    }\n}", "cpp": "bool solution(string s) {\n    return false;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": "A man, a plan, a canal: Panama", "expected": "true"}, {"input": "race a car", "expected": "false"}, {"input": " ", "expected": "true"}],
     "hints": ["Filter out non-alphanumeric characters.", "Use two pointers from both ends."]},

    {"title": "Max Subarray Sum", "difficulty": "easy", "topic": "arrays",
     "description": "Find the contiguous subarray with the largest sum and return its sum. (Kadane's Algorithm)",
     "function_signature": {"python": "def solution(nums):", "java": "public int solution(int[] nums)", "cpp": "int solution(vector<int>& nums)", "c": "int solution(int* nums, int n)"},
     "examples": [{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "output": "6", "explanation": "[4,-1,2,1] has largest sum"}],
     "constraints": ["1 <= nums.length <= 10^5"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public int solution(int[] nums) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& nums) {\n    return 0;\n}", "c": "int solution(int* nums, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[-2,1,-3,4,-1,2,1,-5,4]", "expected": "6"}, {"input": "[1]", "expected": "1"}, {"input": "[5,4,-1,7,8]", "expected": "23"}],
     "hints": ["Keep track of current sum, reset if negative.", "Update max sum at each step."]},

    {"title": "FizzBuzz", "difficulty": "easy", "topic": "basic_logic",
     "description": "Return an array from 1 to n where multiples of 3 are Fizz, multiples of 5 are Buzz, and multiples of both are FizzBuzz.",
     "function_signature": {"python": "def solution(n):", "java": "public List<String> solution(int n)", "cpp": "vector<string> solution(int n)", "c": "char** solution(int n, int* returnSize)"},
     "examples": [{"input": "5", "output": "[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\"]", "explanation": ""}],
     "constraints": ["1 <= n <= 10^4"],
     "starter_code": {"python": "def solution(n):\n    pass", "javascript": "function solution(n) {}", "java": "class Solution {\n    public List<String> solution(int n) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<string> solution(int n) {\n    return {};\n}", "c": "char** solution(int n, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "5", "expected": "[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\"]"}, {"input": "3", "expected": "[\"1\",\"2\",\"Fizz\"]"}, {"input": "15", "expected": "[\"1\",\"2\",\"Fizz\",\"4\",\"Buzz\",\"Fizz\",\"7\",\"8\",\"Fizz\",\"Buzz\",\"11\",\"Fizz\",\"13\",\"14\",\"FizzBuzz\"]"}],
     "hints": ["Check divisibility by 3 and 5 separately.", "Check 15 first to avoid overlapping conditions."]},

    {"title": "Count Vowels", "difficulty": "easy", "topic": "strings",
     "description": "Count the number of vowels in a given string.",
     "function_signature": {"python": "def solution(s):", "java": "public int solution(String s)", "cpp": "int solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "hello", "output": "2", "explanation": "e and o are vowels"}],
     "constraints": ["1 <= s.length <= 10^5"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public int solution(String s) {\n        return 0;\n    }\n}", "cpp": "int solution(string s) {\n    return 0;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": "hello", "expected": "2"}, {"input": "aeiou", "expected": "5"}, {"input": "xyz", "expected": "0"}],
     "hints": ["Create a set of vowels.", "Iterate and count matches."]},

    {"title": "Find Minimum in Rotated Array", "difficulty": "easy", "topic": "arrays",
     "description": "Find the minimum element in a sorted rotated array.",
     "function_signature": {"python": "def solution(nums):", "java": "public int solution(int[] nums)", "cpp": "int solution(vector<int>& nums)", "c": "int solution(int* nums, int n)"},
     "examples": [{"input": "[3,4,5,1,2]", "output": "1", "explanation": "Minimum is 1"}],
     "constraints": ["1 <= nums.length <= 10^4"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public int solution(int[] nums) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& nums) {\n    return 0;\n}", "c": "int solution(int* nums, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[3,4,5,1,2]", "expected": "1"}, {"input": "[2,3,4,5,1]", "expected": "1"}, {"input": "[1]", "expected": "1"}],
     "hints": ["Use binary search.", "Compare mid element with the last element."]},

    {"title": "Merge Sorted Arrays", "difficulty": "easy", "topic": "arrays",
     "description": "Merge two sorted arrays into one sorted array.",
     "function_signature": {"python": "def solution(nums1, nums2):", "java": "public ArrayList<Integer> solution(ArrayList<Integer> nums1, ArrayList<Integer> nums2)", "cpp": "vector<int> solution(vector<int> nums1, vector<int> nums2)", "c": "int* solution(int* nums1, int n1, int* nums2, int n2, int* returnSize)"},
     "examples": [{"input": "[1,3,5]\n[2,4,6]", "output": "[1,2,3,4,5,6]", "explanation": ""}],
     "constraints": ["0 <= nums1.length, nums2.length <= 10^4"],
     "starter_code": {"python": "def solution(nums1, nums2):\n    pass", "javascript": "function solution(nums1, nums2) {}", "java": "class Solution {\n    public ArrayList<Integer> solution(ArrayList<Integer> nums1, ArrayList<Integer> nums2) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<int> solution(vector<int> nums1, vector<int> nums2) {\n    return {};\n}", "c": "int* solution(int* nums1, int n1, int* nums2, int n2, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[1,3,5]\n[2,4,6]", "expected": "[1,2,3,4,5,6]"}, {"input": "[1,2,3]\n[4,5,6]", "expected": "[1,2,3,4,5,6]"}, {"input": "[]\n[1]", "expected": "[1]"}],
     "hints": ["Use two pointers, one for each array.", "Compare and append the smaller element."]},

    {"title": "First Non-Repeating Character", "difficulty": "easy", "topic": "strings",
     "description": "Find the first non-repeating character in a string and return its index.",
     "function_signature": {"python": "def solution(s):", "java": "public int solution(String s)", "cpp": "int solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "leetcode", "output": "0", "explanation": "l is the first non-repeating character"}],
     "constraints": ["1 <= s.length <= 10^5"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public int solution(String s) {\n        return -1;\n    }\n}", "cpp": "int solution(string s) {\n    return -1;\n}", "c": "int solution(char* s) {\n    return -1;\n}"},
     "test_cases": [{"input": "leetcode", "expected": "0"}, {"input": "aabb", "expected": "-1"}, {"input": "loveleetcode", "expected": "2"}],
     "hints": ["Count character frequencies first.", "Then find the first character with count 1."]},

    {"title": "Power of Two", "difficulty": "easy", "topic": "math",
     "description": "Determine if an integer is a power of two.",
     "function_signature": {"python": "def solution(n):", "java": "public boolean solution(int n)", "cpp": "bool solution(int n)", "c": "int solution(int n)"},
     "examples": [{"input": "16", "output": "true", "explanation": "16 = 2^4"}],
     "constraints": ["-2^31 <= n <= 2^31 - 1"],
     "starter_code": {"python": "def solution(n):\n    pass", "javascript": "function solution(n) {}", "java": "class Solution {\n    public boolean solution(int n) {\n        return false;\n    }\n}", "cpp": "bool solution(int n) {\n    return false;\n}", "c": "int solution(int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "16", "expected": "true"}, {"input": "3", "expected": "false"}, {"input": "1", "expected": "true"}],
     "hints": ["Keep dividing by 2.", "Or use bit manipulation: n & (n-1) == 0."]},

    {"title": "Sum of Digits", "difficulty": "easy", "topic": "math",
     "description": "Given a non-negative integer, return the sum of its digits.",
     "function_signature": {"python": "def solution(n):", "java": "public int solution(int n)", "cpp": "int solution(int n)", "c": "int solution(int n)"},
     "examples": [{"input": "123", "output": "6", "explanation": "1+2+3=6"}],
     "constraints": ["0 <= n <= 10^9"],
     "starter_code": {"python": "def solution(n):\n    pass", "javascript": "function solution(n) {}", "java": "class Solution {\n    public int solution(int n) {\n        return 0;\n    }\n}", "cpp": "int solution(int n) {\n    return 0;\n}", "c": "int solution(int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "123", "expected": "6"}, {"input": "0", "expected": "0"}, {"input": "9999", "expected": "36"}],
     "hints": ["Use modulo 10 to get last digit.", "Divide by 10 to remove last digit."]},

    {"title": "Contains Duplicate", "difficulty": "easy", "topic": "arrays",
     "description": "Given an integer array, return true if any value appears at least twice.",
     "function_signature": {"python": "def solution(nums):", "java": "public boolean solution(int[] nums)", "cpp": "bool solution(vector<int>& nums)", "c": "int solution(int* nums, int n)"},
     "examples": [{"input": "[1,2,3,1]", "output": "true", "explanation": "1 appears twice"}],
     "constraints": ["1 <= nums.length <= 10^5"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public boolean solution(int[] nums) {\n        return false;\n    }\n}", "cpp": "bool solution(vector<int>& nums) {\n    return false;\n}", "c": "int solution(int* nums, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[1,2,3,1]", "expected": "true"}, {"input": "[1,2,3,4]", "expected": "false"}, {"input": "[1,1,1,3,3,4,3,2,4,2]", "expected": "true"}],
     "hints": ["Use a HashSet.", "If element already in set, return true."]},

    {"title": "Fibonacci Number", "difficulty": "easy", "topic": "math",
     "description": "Return the nth Fibonacci number. F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2).",
     "function_signature": {"python": "def solution(n):", "java": "public int solution(int n)", "cpp": "int solution(int n)", "c": "int solution(int n)"},
     "examples": [{"input": "10", "output": "55", "explanation": "F(10) = 55"}],
     "constraints": ["0 <= n <= 30"],
     "starter_code": {"python": "def solution(n):\n    pass", "javascript": "function solution(n) {}", "java": "class Solution {\n    public int solution(int n) {\n        return 0;\n    }\n}", "cpp": "int solution(int n) {\n    return 0;\n}", "c": "int solution(int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "10", "expected": "55"}, {"input": "0", "expected": "0"}, {"input": "5", "expected": "5"}],
     "hints": ["Iterative approach with two variables.", "Or use recursion with memoization."]},

    {"title": "Remove Duplicates from Sorted Array", "difficulty": "easy", "topic": "arrays",
     "description": "Remove duplicates in-place and return the new length.",
     "function_signature": {"python": "def solution(nums):", "java": "public int solution(int[] nums)", "cpp": "int solution(vector<int>& nums)", "c": "int solution(int* nums, int n)"},
     "examples": [{"input": "[1,1,2]", "output": "2", "explanation": "New length is 2"}],
     "constraints": ["0 <= nums.length <= 3*10^4"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public int solution(int[] nums) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& nums) {\n    return 0;\n}", "c": "int solution(int* nums, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[1,1,2]", "expected": "2"}, {"input": "[0,0,1,1,1,2,2,3,3,4]", "expected": "5"}, {"input": "[]", "expected": "0"}],
     "hints": ["Use two pointers.", "One pointer for unique elements, one for scanning."]},

    # ── MEDIUM (20) ──
    {"title": "Longest Substring Without Repeating Characters", "difficulty": "medium", "topic": "strings",
     "description": "Find the length of the longest substring without repeating characters.",
     "function_signature": {"python": "def solution(s):", "java": "public int solution(String s)", "cpp": "int solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "abcabcbb", "output": "3", "explanation": "abc is the longest"}],
     "constraints": ["0 <= s.length <= 5*10^4"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public int solution(String s) {\n        return 0;\n    }\n}", "cpp": "int solution(string s) {\n    return 0;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": "abcabcbb", "expected": "3"}, {"input": "bbbbb", "expected": "1"}, {"input": "pwwkew", "expected": "3"}],
     "hints": ["Use sliding window with a HashSet.", "Move left pointer when duplicate found."]},

    {"title": "Product of Array Except Self", "difficulty": "medium", "topic": "arrays",
     "description": "Return an array where each element is the product of all other elements.",
     "function_signature": {"python": "def solution(nums):", "java": "public int[] solution(int[] nums)", "cpp": "vector<int> solution(vector<int>& nums)", "c": "int* solution(int* nums, int n, int* returnSize)"},
     "examples": [{"input": "[1,2,3,4]", "output": "[24,12,8,6]", "explanation": ""}],
     "constraints": ["2 <= nums.length <= 10^5"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public int[] solution(int[] nums) {\n        return new int[]{};\n    }\n}", "cpp": "vector<int> solution(vector<int>& nums) {\n    return {};\n}", "c": "int* solution(int* nums, int n, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[1,2,3,4]", "expected": "[24,12,8,6]"}, {"input": "[-1,1,0,-3,3]", "expected": "[0,0,9,0,0]"}],
     "hints": ["Calculate prefix products and suffix products.", "Combine them without using division."]},

    {"title": "Group Anagrams", "difficulty": "medium", "topic": "strings",
     "description": "Group strings that are anagrams of each other.",
     "function_signature": {"python": "def solution(strs):", "java": "public List<List<String>> solution(String[] strs)", "cpp": "vector<vector<string>> solution(vector<string>& strs)", "c": "char*** solution(char** strs, int n, int* returnSize)"},
     "examples": [{"input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "output": "[[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]", "explanation": ""}],
     "constraints": ["1 <= strs.length <= 10^4"],
     "starter_code": {"python": "def solution(strs):\n    pass", "javascript": "function solution(strs) {}", "java": "class Solution {\n    public List<List<String>> solution(String[] strs) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<vector<string>> solution(vector<string>& strs) {\n    return {};\n}", "c": "char*** solution(char** strs, int n, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", "expected": "[[\"eat\",\"tea\",\"ate\"],[\"tan\",\"nat\"],[\"bat\"]]"}, {"input": "[\"\"]", "expected": "[[\"\"]]"}, {"input": "[\"a\"]", "expected": "[[\"a\"]]"}],
     "hints": ["Sort each string to get the key.", "Use a dictionary to group by sorted key."]},

    {"title": "Top K Frequent Elements", "difficulty": "medium", "topic": "arrays",
     "description": "Return the k most frequent elements from an array.",
     "function_signature": {"python": "def solution(nums, k):", "java": "public int[] solution(int[] nums, int k)", "cpp": "vector<int> solution(vector<int>& nums, int k)", "c": "int* solution(int* nums, int n, int k, int* returnSize)"},
     "examples": [{"input": "[1,1,1,2,2,3]\n2", "output": "[1,2]", "explanation": ""}],
     "constraints": ["1 <= nums.length <= 10^5"],
     "starter_code": {"python": "def solution(nums, k):\n    pass", "javascript": "function solution(nums, k) {}", "java": "class Solution {\n    public int[] solution(int[] nums, int k) {\n        return new int[]{};\n    }\n}", "cpp": "vector<int> solution(vector<int>& nums, int k) {\n    return {};\n}", "c": "int* solution(int* nums, int n, int k, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[1,1,1,2,2,3]\n2", "expected": "[1,2]"}, {"input": "[1]\n1", "expected": "[1]"}],
     "hints": ["Count frequencies with a HashMap.", "Use a bucket sort or min-heap approach."]},

    {"title": "Valid Sudoku", "difficulty": "medium", "topic": "arrays",
     "description": "Determine if a 9x9 Sudoku board is valid.",
     "function_signature": {"python": "def solution(board):", "java": "public boolean solution(char[][] board)", "cpp": "bool solution(vector<vector<char>>& board)", "c": "int solution(char board[9][9])"},
     "examples": [{"input": "[[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]", "output": "true", "explanation": ""}],
     "constraints": ["board.length == 9"],
     "starter_code": {"python": "def solution(board):\n    pass", "javascript": "function solution(board) {}", "java": "class Solution {\n    public boolean solution(char[][] board) {\n        return false;\n    }\n}", "cpp": "bool solution(vector<vector<char>>& board) {\n    return false;\n}", "c": "int solution(char board[9][9]) {\n    return 0;\n}"},
     "test_cases": [{"input": "valid_board", "expected": "true"}, {"input": "invalid_board", "expected": "false"}],
     "hints": ["Use sets to track rows, columns, and 3x3 boxes.", "Check each constraint independently."]},

    {"title": "Binary Tree Level Order Traversal", "difficulty": "medium", "topic": "trees",
     "description": "Return level order traversal of a binary tree's nodes' values.",
     "function_signature": {"python": "def solution(root):", "java": "public List<List<Integer>> solution(TreeNode root)", "cpp": "vector<vector<int>> solution(TreeNode* root)", "c": ""},
     "examples": [{"input": "[3,9,20,null,null,15,7]", "output": "[[3],[9,20],[15,7]]", "explanation": ""}],
     "constraints": ["0 <= number of nodes <= 2000"],
     "starter_code": {"python": "def solution(root):\n    pass", "javascript": "function solution(root) {}", "java": "class Solution {\n    public List<List<Integer>> solution(TreeNode root) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<vector<int>> solution(TreeNode* root) {\n    return {};\n}", "c": ""},
     "test_cases": [{"input": "[3,9,20,null,null,15,7]", "expected": "[[3],[9,20],[15,7]]"}, {"input": "[1]", "expected": "[[1]]"}, {"input": "[]", "expected": "[]"}],
     "hints": ["Use BFS with a queue.", "Process level by level."]},

    {"title": "Number of Islands", "difficulty": "medium", "topic": "graphs",
     "description": "Given a 2D grid of '1's (land) and '0's (water), count the number of islands.",
     "function_signature": {"python": "def solution(grid):", "java": "public int solution(char[][] grid)", "cpp": "int solution(vector<vector<char>>& grid)", "c": "int solution(char** grid, int gridSize, int* gridColSize)"},
     "examples": [{"input": "[[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]", "output": "1", "explanation": ""}],
     "constraints": ["1 <= grid.length <= 300"],
     "starter_code": {"python": "def solution(grid):\n    pass", "javascript": "function solution(grid) {}", "java": "class Solution {\n    public int solution(char[][] grid) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<vector<char>>& grid) {\n    return 0;\n}", "c": "int solution(char** grid, int gridSize, int* gridColSize) {\n    return 0;\n}"},
     "test_cases": [{"input": "island_grid", "expected": "1"}, {"input": "multi_island_grid", "expected": "3"}],
     "hints": ["Use DFS or BFS to explore each island.", "Mark visited cells to avoid counting twice."]},

    {"title": "Clone Graph", "difficulty": "medium", "topic": "graphs",
     "description": "Given a reference of a node in a connected undirected graph, return a deep copy of the graph.",
     "function_signature": {"python": "def solution(node):", "java": "public Node solution(Node node)", "cpp": "Node* solution(Node* node)", "c": ""},
     "examples": [{"input": "adjacency_list", "output": "deep_copy", "explanation": ""}],
     "constraints": ["0 <= number of nodes <= 100"],
     "starter_code": {"python": "def solution(node):\n    pass", "javascript": "function solution(node) {}", "java": "class Solution {\n    public Node solution(Node node) {\n        return null;\n    }\n}", "cpp": "Node* solution(Node* node) {\n    return nullptr;\n}", "c": ""},
     "test_cases": [{"input": "graph1", "expected": "deep_copy1"}, {"input": "empty", "expected": "null"}],
     "hints": ["Use a HashMap to map original nodes to copies.", "Use BFS or DFS to traverse and clone."]},

    {"title": "LRU Cache", "difficulty": "medium", "topic": "design",
     "description": "Design a data structure that follows LRU cache constraints.",
     "function_signature": {"python": "class LRUCache:\n    def __init__(self, capacity):", "java": "class LRUCache { public LRUCache(int capacity) {} }", "cpp": "class LRUCache { public: LRUCache(int capacity) {} };", "c": ""},
     "examples": [{"input": "capacity=2, put(1,1), put(2,2), get(1), put(3,3), get(2)", "output": "1, -1", "explanation": ""}],
     "constraints": ["1 <= capacity <= 3000"],
     "starter_code": {"python": "class LRUCache:\n    def __init__(self, capacity):\n        pass", "javascript": "class LRUCache { constructor(capacity) {} }", "java": "class LRUCache {\n    public LRUCache(int capacity) {}\n}", "cpp": "class LRUCache {\npublic:\n    LRUCache(int capacity) {}\n};", "c": ""},
     "test_cases": [{"input": "lru_ops", "expected": "correct_sequence"}, {"input": "overfill", "expected": "eviction_correct"}],
     "hints": ["Use a HashMap + Doubly Linked List.", "HashMap for O(1) access, Linked List for O(1) eviction."]},

    {"title": "Merge Intervals", "difficulty": "medium", "topic": "arrays",
     "description": "Merge all overlapping intervals.",
     "function_signature": {"python": "def solution(intervals):", "java": "public int[][] solution(int[][] intervals)", "cpp": "vector<vector<int>> solution(vector<vector<int>>& intervals)", "c": "int** solution(int** intervals, int n, int* returnSize)"},
     "examples": [{"input": "[[1,3],[2,6],[8,10],[15,18]]", "output": "[[1,6],[8,10],[15,18]]", "explanation": ""}],
     "constraints": ["1 <= intervals.length <= 10^4"],
     "starter_code": {"python": "def solution(intervals):\n    pass", "javascript": "function solution(intervals) {}", "java": "class Solution {\n    public int[][] solution(int[][] intervals) {\n        return new int[][]{};\n    }\n}", "cpp": "vector<vector<int>> solution(vector<vector<int>>& intervals) {\n    return {};\n}", "c": "int** solution(int** intervals, int n, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "[[1,3],[2,6],[8,10],[15,18]]", "expected": "[[1,6],[8,10],[15,18]]"}, {"input": "[[1,4],[4,5]]", "expected": "[[1,5]]"}],
     "hints": ["Sort intervals by start time.", "Merge overlapping intervals iteratively."]},

    {"title": "Subarray Sum Equals K", "difficulty": "medium", "topic": "arrays",
     "description": "Count the number of continuous subarrays whose sum equals k.",
     "function_signature": {"python": "def solution(nums, k):", "java": "public int solution(int[] nums, int k)", "cpp": "int solution(vector<int>& nums, int k)", "c": "int solution(int* nums, int n, int k)"},
     "examples": [{"input": "[1,1,1]\n2", "output": "2", "explanation": ""}],
     "constraints": ["1 <= nums.length <= 2*10^4"],
     "starter_code": {"python": "def solution(nums, k):\n    pass", "javascript": "function solution(nums, k) {}", "java": "class Solution {\n    public int solution(int[] nums, int k) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& nums, int k) {\n    return 0;\n}", "c": "int solution(int* nums, int n, int k) {\n    return 0;\n}"},
     "test_cases": [{"input": "[1,1,1]\n2", "expected": "2"}, {"input": "[1,2,3]\n3", "expected": "2"}],
     "hints": ["Use prefix sum with a HashMap.", "Store prefix sum frequencies."]},

    {"title": "Container With Most Water", "difficulty": "medium", "topic": "arrays",
     "description": "Find two lines that together with the x-axis form a container holding the most water.",
     "function_signature": {"python": "def solution(height):", "java": "public int solution(int[] height)", "cpp": "int solution(vector<int>& height)", "c": "int solution(int* height, int n)"},
     "examples": [{"input": "[1,8,6,2,5,4,8,3,7]", "output": "49", "explanation": ""}],
     "constraints": ["2 <= height.length <= 10^5"],
     "starter_code": {"python": "def solution(height):\n    pass", "javascript": "function solution(height) {}", "java": "class Solution {\n    public int solution(int[] height) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& height) {\n    return 0;\n}", "c": "int solution(int* height, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[1,8,6,2,5,4,8,3,7]", "expected": "49"}, {"input": "[1,1]", "expected": "1"}],
     "hints": ["Use two pointers from both ends.", "Move the pointer pointing to the shorter line."]},

    {"title": "Decode String", "difficulty": "medium", "topic": "strings",
     "description": "Given an encoded string, return its decoded version. s = '3[a2[c]]' returns 'accaccacc'.",
     "function_signature": {"python": "def solution(s):", "java": "public String solution(String s)", "cpp": "string solution(string s)", "c": "char* solution(char* s)"},
     "examples": [{"input": "3[a2[c]]", "output": "accaccacc", "explanation": ""}],
     "constraints": ["1 <= s.length <= 30"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public String solution(String s) {\n        return \"\";\n    }\n}", "cpp": "string solution(string s) {\n    return \"\";\n}", "c": "char* solution(char* s) {\n    return s;\n}"},
     "test_cases": [{"input": "3[a2[c]]", "expected": "accaccacc"}, {"input": "2[abc]3[cd]ef", "expected": "abcabccdcdcdef"}],
     "hints": ["Use a stack to store counts and strings.", "When you see ']', pop and repeat."]},

    {"title": "Coin Change", "difficulty": "medium", "topic": "dp",
     "description": "Given coins of different denominations and a total amount, compute the fewest number of coins needed.",
     "function_signature": {"python": "def solution(coins, amount):", "java": "public int solution(int[] coins, int amount)", "cpp": "int solution(vector<int>& coins, int amount)", "c": "int solution(int* coins, int n, int amount)"},
     "examples": [{"input": "[1,2,5]\n11", "output": "3", "explanation": "5+5+1"}],
     "constraints": ["1 <= coins.length <= 12", "0 <= amount <= 10^4"],
     "starter_code": {"python": "def solution(coins, amount):\n    pass", "javascript": "function solution(coins, amount) {}", "java": "class Solution {\n    public int solution(int[] coins, int amount) {\n        return -1;\n    }\n}", "cpp": "int solution(vector<int>& coins, int amount) {\n    return -1;\n}", "c": "int solution(int* coins, int n, int amount) {\n    return -1;\n}"},
     "test_cases": [{"input": "[1,2,5]\n11", "expected": "3"}, {"input": "[2]\n3", "expected": "-1"}, {"input": "[1]\n0", "expected": "0"}],
     "hints": ["Use dynamic programming.", "dp[i] = min coins to make amount i."]},

    {"title": "Longest Increasing Subsequence", "difficulty": "medium", "topic": "dp",
     "description": "Find the length of the longest strictly increasing subsequence.",
     "function_signature": {"python": "def solution(nums):", "java": "public int solution(int[] nums)", "cpp": "int solution(vector<int>& nums)", "c": "int solution(int* nums, int n)"},
     "examples": [{"input": "[10,9,2,5,3,7,101,18]", "output": "4", "explanation": "[2,3,7,101]"}],
     "constraints": ["1 <= nums.length <= 2500"],
     "starter_code": {"python": "def solution(nums):\n    pass", "javascript": "function solution(nums) {}", "java": "class Solution {\n    public int solution(int[] nums) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& nums) {\n    return 0;\n}", "c": "int solution(int* nums, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[10,9,2,5,3,7,101,18]", "expected": "4"}, {"input": "[0,1,0,3,2,3]", "expected": "4"}, {"input": "[7,7,7,7,7,7,7]", "expected": "1"}],
     "hints": ["O(n^2) DP approach: for each element, check all previous.", "O(n log n) approach using binary search with a tails array."]},

    {"title": "Word Search", "difficulty": "medium", "topic": "backtracking",
     "description": "Given a 2D board and a word, find if the word exists in the grid.",
     "function_signature": {"python": "def solution(board, word):", "java": "public boolean solution(char[][] board, String word)", "cpp": "bool solution(vector<vector<char>>& board, string word)", "c": "int solution(char** board, int boardSize, int* boardColSize, char* word)"},
     "examples": [{"input": "[[A,B,C,E],[S,F,C,S],[A,D,E,E]]\nABCCED", "output": "true", "explanation": ""}],
     "constraints": ["m, n <= 6"],
     "starter_code": {"python": "def solution(board, word):\n    pass", "javascript": "function solution(board, word) {}", "java": "class Solution {\n    public boolean solution(char[][] board, String word) {\n        return false;\n    }\n}", "cpp": "bool solution(vector<vector<char>>& board, string word) {\n    return false;\n}", "c": "int solution(char** board, int boardSize, int* boardColSize, char* word) {\n    return 0;\n}"},
     "test_cases": [{"input": "board1,ABCCED", "expected": "true"}, {"input": "board1,ABCB", "expected": "false"}],
     "hints": ["Use DFS/backtracking.", "Mark visited cells and unmark on backtracking."]},

    {"title": "Implement Trie (Prefix Tree)", "difficulty": "medium", "topic": "design",
     "description": "Implement a trie with insert, search, and startsWith methods.",
     "function_signature": {"python": "class Trie:\n    def __init__(self):", "java": "class Trie { public Trie() {} }", "cpp": "class Trie { public: Trie() {} };", "c": ""},
     "examples": [{"input": "insert('apple'), search('apple'), startsWith('app')", "output": "true, true", "explanation": ""}],
     "constraints": ["1 <= word.length <= 2000"],
     "starter_code": {"python": "class Trie:\n    def __init__(self):\n        pass", "javascript": "class Trie { constructor() {} }", "java": "class Trie {\n    public Trie() {}\n}", "cpp": "class Trie {\npublic:\n    Trie() {}\n};", "c": ""},
     "test_cases": [{"input": "trie_ops", "expected": "correct_results"}, {"input": "prefix_search", "expected": "correct_results"}],
     "hints": ["Each node has a HashMap of children.", "Mark end of word with a boolean."]},

    {"title": "Find All Anagrams in a String", "difficulty": "medium", "topic": "strings",
     "description": "Find all start indices of p's anagrams in s.",
     "function_signature": {"python": "def solution(s, p):", "java": "public List<Integer> solution(String s, String p)", "cpp": "vector<int> solution(string s, string p)", "c": "int* solution(char* s, char* p, int* returnSize)"},
     "examples": [{"input": "cbaebabacd\nabc", "output": "[0,6]", "explanation": ""}],
     "constraints": ["1 <= s.length, p.length <= 3*10^4"],
     "starter_code": {"python": "def solution(s, p):\n    pass", "javascript": "function solution(s, p) {}", "java": "class Solution {\n    public List<Integer> solution(String s, String p) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<int> solution(string s, string p) {\n    return {};\n}", "c": "int* solution(char* s, char* p, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "cbaebabacd\nabc", "expected": "[0,6]"}, {"input": "abab\nab", "expected": "[0,1,2]"}],
     "hints": ["Use sliding window of size len(p).", "Compare character frequency counts."]},

    {"title": "Rotting Oranges", "difficulty": "medium", "topic": "graphs",
     "description": "Return the minimum number of minutes until no fresh orange is left. Each minute, rotten oranges rot adjacent fresh oranges.",
     "function_signature": {"python": "def solution(grid):", "java": "public int solution(int[][] grid)", "cpp": "int solution(vector<vector<int>>& grid)", "c": "int solution(int** grid, int gridSize, int* gridColSize)"},
     "examples": [{"input": "[[2,1,1],[1,1,0],[0,1,1]]", "output": "4", "explanation": ""}],
     "constraints": ["1 <= grid.length, grid[0].length <= 10"],
     "starter_code": {"python": "def solution(grid):\n    pass", "javascript": "function solution(grid) {}", "java": "class Solution {\n    public int solution(int[][] grid) {\n        return -1;\n    }\n}", "cpp": "int solution(vector<vector<int>>& grid) {\n    return -1;\n}", "c": "int solution(int** grid, int gridSize, int* gridColSize) {\n    return -1;\n}"},
     "test_cases": [{"input": "rotten_grid1", "expected": "4"}, {"input": "rotten_grid2", "expected": "0"}],
     "hints": ["Use BFS starting from all rotten oranges simultaneously.", "Track time as BFS levels."]},

    # ── HARD (15) ──
    {"title": "Median of Two Sorted Arrays", "difficulty": "hard", "topic": "arrays",
     "description": "Find the median of two sorted arrays in O(log(m+n)) time.",
     "function_signature": {"python": "def solution(nums1, nums2):", "java": "public double solution(int[] nums1, int[] nums2)", "cpp": "double solution(vector<int>& nums1, vector<int>& nums2)", "c": "double solution(int* nums1, int n1, int* nums2, int n2)"},
     "examples": [{"input": "[1,3]\n[2]", "output": "2.0", "explanation": ""}],
     "constraints": ["0 <= m, n <= 10^6"],
     "starter_code": {"python": "def solution(nums1, nums2):\n    pass", "javascript": "function solution(nums1, nums2) {}", "java": "class Solution {\n    public double solution(int[] nums1, int[] nums2) {\n        return 0.0;\n    }\n}", "cpp": "double solution(vector<int>& nums1, vector<int>& nums2) {\n    return 0.0;\n}", "c": "double solution(int* nums1, int n1, int* nums2, int n2) {\n    return 0.0;\n}"},
     "test_cases": [{"input": "[1,3]\n[2]", "expected": "2.0"}, {"input": "[1,2]\n[3,4]", "expected": "2.5"}],
     "hints": ["Binary search on the smaller array.", "Partition both arrays so left half has equal elements."]},

    {"title": "Trapping Rain Water", "difficulty": "hard", "topic": "arrays",
     "description": "Compute how much water it can trap after raining.",
     "function_signature": {"python": "def solution(height):", "java": "public int solution(int[] height)", "cpp": "int solution(vector<int>& height)", "c": "int solution(int* height, int n)"},
     "examples": [{"input": "[0,1,0,2,1,0,1,3,2,1,2,1]", "output": "6", "explanation": ""}],
     "constraints": ["1 <= height.length <= 2*10^4"],
     "starter_code": {"python": "def solution(height):\n    pass", "javascript": "function solution(height) {}", "java": "class Solution {\n    public int solution(int[] height) {\n        return 0;\n    }\n}", "cpp": "int solution(vector<int>& height) {\n    return 0;\n}", "c": "int solution(int* height, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[0,1,0,2,1,0,1,3,2,1,2,1]", "expected": "6"}, {"input": "[4,2,0,3,2,5]", "expected": "9"}],
     "hints": ["Use two pointers from both ends.", "Track left_max and right_max."]},

    {"title": "Merge k Sorted Lists", "difficulty": "hard", "topic": "linked_list",
     "description": "Merge k sorted linked lists and return it as one sorted list.",
     "function_signature": {"python": "def solution(lists):", "java": "public ListNode solution(ListNode[] lists)", "cpp": "ListNode* solution(vector<ListNode*>& lists)", "c": ""},
     "examples": [{"input": "[[1,4,5],[1,3,4],[2,6]]", "output": "[1,1,2,3,4,4,5,6]", "explanation": ""}],
     "constraints": ["k == lists.length", "0 <= lists[i].length <= 500"],
     "starter_code": {"python": "def solution(lists):\n    pass", "javascript": "function solution(lists) {}", "java": "class Solution {\n    public ListNode solution(ListNode[] lists) {\n        return null;\n    }\n}", "cpp": "ListNode* solution(vector<ListNode*>& lists) {\n    return nullptr;\n}", "c": ""},
     "test_cases": [{"input": "lists1", "expected": "merged1"}, {"input": "empty", "expected": "null"}],
     "hints": ["Use a min-heap (priority queue).", "Or use divide and conquer approach."]},

    {"title": "Regular Expression Matching", "difficulty": "hard", "topic": "dp",
     "description": "Implement regular expression matching with support for '.' and '*'.",
     "function_signature": {"python": "def solution(s, p):", "java": "public boolean solution(String s, String p)", "cpp": "bool solution(string s, string p)", "c": "int solution(char* s, char* p)"},
     "examples": [{"input": "aa\na", "output": "false", "explanation": ""}, {"input": "aa\na*", "output": "true", "explanation": ""}],
     "constraints": ["1 <= s.length, p.length <= 20"],
     "starter_code": {"python": "def solution(s, p):\n    pass", "javascript": "function solution(s, p) {}", "java": "class Solution {\n    public boolean solution(String s, String p) {\n        return false;\n    }\n}", "cpp": "bool solution(string s, string p) {\n    return false;\n}", "c": "int solution(char* s, char* p) {\n    return 0;\n}"},
     "test_cases": [{"input": "aa\na", "expected": "false"}, {"input": "aa\na*", "expected": "true"}, {"input": "ab\n.*", "expected": "true"}],
     "hints": ["Use 2D DP.", "Handle '*' by matching 0 or more of the preceding character."]},

    {"title": "Word Ladder", "difficulty": "hard", "topic": "graphs",
     "description": "Find the length of the shortest transformation sequence from beginWord to endWord.",
     "function_signature": {"python": "def solution(beginWord, endWord, wordList):", "java": "public int solution(String beginWord, String endWord, List<String> wordList)", "cpp": "int solution(string beginWord, string endWord, vector<string>& wordList)", "c": "int solution(char* beginWord, char* endWord, char** wordList, int wordListSize)"},
     "examples": [{"input": "hit\ncog\n[hot,dot,dog,lot,log,cog]", "output": "5", "explanation": "hit->hot->dot->dog->cog"}],
     "constraints": ["1 <= beginWord.length <= 10"],
     "starter_code": {"python": "def solution(beginWord, endWord, wordList):\n    pass", "javascript": "function solution(beginWord, endWord, wordList) {}", "java": "class Solution {\n    public int solution(String beginWord, String endWord, List<String> wordList) {\n        return 0;\n    }\n}", "cpp": "int solution(string beginWord, string endWord, vector<string>& wordList) {\n    return 0;\n}", "c": "int solution(char* beginWord, char* endWord, char** wordList, int wordListSize) {\n    return 0;\n}"},
     "test_cases": [{"input": "hit\ncog\nwordList1", "expected": "5"}, {"input": "hit\ncog\n[]", "expected": "0"}],
     "hints": ["Use BFS for shortest path.", "Transform one letter at a time and check wordList."]},

    {"title": "N-Queens", "difficulty": "hard", "topic": "backtracking",
     "description": "Place n queens on an n x n chessboard such that no two queens attack each other.",
     "function_signature": {"python": "def solution(n):", "java": "public List<List<String>> solution(int n)", "cpp": "vector<vector<string>> solution(int n)", "c": ""},
     "examples": [{"input": "4", "output": "2 distinct solutions", "explanation": ""}],
     "constraints": ["1 <= n <= 9"],
     "starter_code": {"python": "def solution(n):\n    pass", "javascript": "function solution(n) {}", "java": "class Solution {\n    public List<List<String>> solution(int n) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<vector<string>> solution(int n) {\n    return {};\n}", "c": ""},
     "test_cases": [{"input": "4", "expected": "2_solutions"}, {"input": "1", "expected": "1_solution"}],
     "hints": ["Use backtracking.", "Track columns, diagonals, and anti-diagonals."]},

    {"title": "Serialize and Deserialize Binary Tree", "difficulty": "hard", "topic": "trees",
     "description": "Design an algorithm to serialize and deserialize a binary tree.",
     "function_signature": {"python": "class Codec:\n    def serialize(self, root):", "java": "class Codec { public String serialize(TreeNode root) {} }", "cpp": "class Codec { public: string serialize(TreeNode* root) {} };", "c": ""},
     "examples": [{"input": "[1,2,3,null,null,4,5]", "output": "serialized_string", "explanation": ""}],
     "constraints": ["0 <= number of nodes <= 10^4"],
     "starter_code": {"python": "class Codec:\n    def serialize(self, root):\n        pass", "javascript": "class Codec { serialize(root) {} }", "java": "class Codec {\n    public String serialize(TreeNode root) {\n        return \"\";\n    }\n}", "cpp": "class Codec {\npublic:\n    string serialize(TreeNode* root) {\n        return \"\";\n    }\n};", "c": ""},
     "test_cases": [{"input": "tree1", "expected": "roundtrip_works"}, {"input": "null", "expected": "null"}],
     "hints": ["Use preorder traversal for serialization.", "Use a queue for deserialization."]},

    {"title": "Alien Dictionary", "difficulty": "hard", "topic": "graphs",
     "description": "Given a sorted list of words from an alien language, derive the character order.",
     "function_signature": {"python": "def solution(words):", "java": "public String solution(String[] words)", "cpp": "string solution(vector<string>& words)", "c": "char* solution(char** words, int n)"},
     "examples": [{"input": "[\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]", "output": "wertf", "explanation": ""}],
     "constraints": ["2 <= words.length <= 100"],
     "starter_code": {"python": "def solution(words):\n    pass", "javascript": "function solution(words) {}", "java": "class Solution {\n    public String solution(String[] words) {\n        return \"\";\n    }\n}", "cpp": "string solution(vector<string>& words) {\n    return \"\";\n}", "c": "char* solution(char** words, int n) {\n    return \"\";\n}"},
     "test_cases": [{"input": "words1", "expected": "wertf"}, {"input": "words2", "expected": "z"}],
     "hints": ["Build a directed graph from character comparisons.", "Use topological sort (Kahn's algorithm)."]},

    {"title": "Longest Valid Parentheses", "difficulty": "hard", "topic": "dp",
     "description": "Find the length of the longest valid (well-formed) parentheses substring.",
     "function_signature": {"python": "def solution(s):", "java": "public int solution(String s)", "cpp": "int solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": ")()())", "output": "4", "explanation": "()()"}],
     "constraints": ["0 <= s.length <= 3*10^4"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public int solution(String s) {\n        return 0;\n    }\n}", "cpp": "int solution(string s) {\n    return 0;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": ")()())", "expected": "4"}, {"input": "()()", "expected": "4"}, {"input": "(()", "expected": "2"}],
     "hints": ["Use a stack storing indices.", "Or use DP: dp[i] = length of longest valid ending at i."]},

    {"title": "Minimum Window Substring", "difficulty": "hard", "topic": "strings",
     "description": "Find the minimum window in s which will contain all the characters of t.",
     "function_signature": {"python": "def solution(s, t):", "java": "public String solution(String s, String t)", "cpp": "string solution(string s, string t)", "c": "char* solution(char* s, char* t)"},
     "examples": [{"input": "ADOBECODEBANC\nABC", "output": "BANC", "explanation": ""}],
     "constraints": ["m, n <= 10^5"],
     "starter_code": {"python": "def solution(s, t):\n    pass", "javascript": "function solution(s, t) {}", "java": "class Solution {\n    public String solution(String s, String t) {\n        return \"\";\n    }\n}", "cpp": "string solution(string s, string t) {\n    return \"\";\n}", "c": "char* solution(char* s, char* t) {\n    return s;\n}"},
     "test_cases": [{"input": "ADOBECODEBANC\nABC", "expected": "BANC"}, {"input": "a\na", "expected": "a"}, {"input": "a\naa", "expected": ""}],
     "hints": ["Use sliding window with two pointers.", "Track character counts and when all matched."]},

    {"title": "Course Schedule II", "difficulty": "hard", "topic": "graphs",
     "description": "Return the ordering of courses you should take to finish all courses (topological sort).",
     "function_signature": {"python": "def solution(numCourses, prerequisites):", "java": "public int[] solution(int numCourses, int[][] prerequisites)", "cpp": "vector<int> solution(int numCourses, vector<vector<int>>& prerequisites)", "c": "int* solution(int numCourses, int** prerequisites, int prerequisitesSize, int* returnSize)"},
     "examples": [{"input": "4\n[[1,0],[2,0],[3,1],[3,2]]", "output": "[0,1,2,3] or [0,2,1,3]", "explanation": ""}],
     "constraints": ["1 <= numCourses <= 2000"],
     "starter_code": {"python": "def solution(numCourses, prerequisites):\n    pass", "javascript": "function solution(numCourses, prerequisites) {}", "java": "class Solution {\n    public int[] solution(int numCourses, int[][] prerequisites) {\n        return new int[]{};\n    }\n}", "cpp": "vector<int> solution(int numCourses, vector<vector<int>>& prerequisites) {\n    return {};\n}", "c": "int* solution(int numCourses, int** prerequisites, int prerequisitesSize, int* returnSize) {\n    *returnSize = 0;\n    return NULL;\n}"},
     "test_cases": [{"input": "4,prereq1", "expected": "valid_order"}, {"input": "2,[[1,0]]", "expected": "[0,1]"}],
     "hints": ["Use Kahn's algorithm (BFS-based topological sort).", "Track in-degrees of all nodes."]},

    {"title": "Basic Calculator II", "difficulty": "hard", "topic": "stack",
     "description": "Implement a basic calculator to evaluate a simple expression string containing +, -, *, /.",
     "function_signature": {"python": "def solution(s):", "java": "public int solution(String s)", "cpp": "int solution(string s)", "c": "int solution(char* s)"},
     "examples": [{"input": "3+2*2", "output": "7", "explanation": ""}],
     "constraints": ["1 <= s.length <= 3*10^5"],
     "starter_code": {"python": "def solution(s):\n    pass", "javascript": "function solution(s) {}", "java": "class Solution {\n    public int solution(String s) {\n        return 0;\n    }\n}", "cpp": "int solution(string s) {\n    return 0;\n}", "c": "int solution(char* s) {\n    return 0;\n}"},
     "test_cases": [{"input": "3+2*2", "expected": "7"}, {"input": " 3/2 ", "expected": "1"}, {"input": "3+5 / 2", "expected": "5"}],
     "hints": ["Use a stack to store numbers.", "Handle operator precedence: * and / before + and -."]},

    {"title": "Skyline Problem", "difficulty": "hard", "topic": "heap",
     "description": "The skyline of a city is formed by the contours of buildings. Return the skyline formed.",
     "function_signature": {"python": "def solution(buildings):", "java": "public List<List<Integer>> solution(int[][] buildings)", "cpp": "vector<vector<int>> solution(vector<vector<int>>& buildings)", "c": ""},
     "examples": [{"input": "[[2,9,10],[3,7,15],[5,12,12],[15,20,10],[19,24,8]]", "output": "[[2,10],[3,15],[7,12],[12,0],[15,10],[20,8],[24,0]]", "explanation": ""}],
     "constraints": ["1 <= buildings.length <= 10^4"],
     "starter_code": {"python": "def solution(buildings):\n    pass", "javascript": "function solution(buildings) {}", "java": "class Solution {\n    public List<List<Integer>> solution(int[][] buildings) {\n        return new ArrayList<>();\n    }\n}", "cpp": "vector<vector<int>> solution(vector<vector<int>>& buildings) {\n    return {};\n}", "c": ""},
     "test_cases": [{"input": "buildings1", "expected": "skyline1"}, {"input": "buildings2", "expected": "skyline2"}],
     "hints": ["Use a sweep line algorithm.", "Process start and end events, use a multiset for heights."]},

    {"title": "Edit Distance", "difficulty": "hard", "topic": "dp",
     "description": "Given two strings, find the minimum number of operations (insert, delete, replace) to convert word1 to word2.",
     "function_signature": {"python": "def solution(word1, word2):", "java": "public int solution(String word1, String word2)", "cpp": "int solution(string word1, string word2)", "c": "int solution(char* word1, char* word2)"},
     "examples": [{"input": "horse\nros", "output": "3", "explanation": "horse->ror->ros"}],
     "constraints": ["0 <= word1.length, word2.length <= 500"],
     "starter_code": {"python": "def solution(word1, word2):\n    pass", "javascript": "function solution(word1, word2) {}", "java": "class Solution {\n    public int solution(String word1, String word2) {\n        return 0;\n    }\n}", "cpp": "int solution(string word1, string word2) {\n    return 0;\n}", "c": "int solution(char* word1, char* word2) {\n    return 0;\n}"},
     "test_cases": [{"input": "horse\nros", "expected": "3"}, {"input": "intention\nexecution", "expected": "5"}],
     "hints": ["Use 2D DP table.", "dp[i][j] = min operations to convert word1[0..i] to word2[0..j]."]},

    {"title": "Frog Jump", "difficulty": "hard", "topic": "dp",
     "description": "Determine if the frog can cross the river by landing on the last stone.",
     "function_signature": {"python": "def solution(stones):", "java": "public boolean solution(int[] stones)", "cpp": "bool solution(vector<int>& stones)", "c": "int solution(int* stones, int n)"},
     "examples": [{"input": "[0,1,3,5,6,7,8,9,10]", "output": "true", "explanation": ""}],
     "constraints": ["2 <= stones.length <= 1100"],
     "starter_code": {"python": "def solution(stones):\n    pass", "javascript": "function solution(stones) {}", "java": "class Solution {\n    public boolean solution(int[] stones) {\n        return false;\n    }\n}", "cpp": "bool solution(vector<int>& stones) {\n    return false;\n}", "c": "int solution(int* stones, int n) {\n    return 0;\n}"},
     "test_cases": [{"input": "[0,1,3,5,6,7,8,9,10]", "expected": "true"}, {"input": "[0,1,2,3,4,8,9,11]", "expected": "false"}],
     "hints": ["Use DP with a HashMap.", "dp[stone] = set of jump sizes that can reach it."]},
]


def build_coding_problems_docs():
    """coding_problems collection ke liye documents banao."""
    docs = []
    for p in CODING_PROBLEMS:
        docs.append({
            "title": p["title"],
            "difficulty": p["difficulty"],
            "topic": p["topic"],
            "description": p["description"],
            "function_signature": p["function_signature"],
            "examples": p["examples"],
            "constraints": p["constraints"],
            "starter_code": p["starter_code"],
            "test_cases": p["test_cases"],
            "hints": p["hints"],
            "attempted": 0,
            "solved": 0,
            "avg_score": 0.0,
            "total_score_sum": 0.0,
            "times_scored": 0,
        })
    return docs


# ══════════════════════════════════════════════════════════════
# SECTION 3: HR QUESTIONS (hr_questions)
# 100 questions: 40 behavioral, 30 situational, 30 motivational
# ══════════════════════════════════════════════════════════════

HR_BEHAVIORAL = [
    "Tell me about yourself and why you are interested in this role",
    "What are your greatest strengths and weaknesses?",
    "Where do you see yourself in 5 years?",
    "Why should we hire you for this position?",
    "Tell me about a time you demonstrated leadership",
    "How do you handle stress and pressure at work?",
    "Describe your ideal work environment",
    "Tell me about a time you failed and what you learned from it",
    "What motivates you in your professional life?",
    "How do you handle conflict with a teammate or manager?",
    "Tell me about a time you had to meet a tight deadline",
    "Describe a situation where you went above and beyond",
    "How do you prioritize tasks when everything feels urgent?",
    "Tell me about a project you are most proud of and why",
    "Do you have any questions for us about the company or role?",
    "Why are you interested in this company specifically?",
    "How do you handle receiving constructive criticism?",
    "Describe a time you had to adapt to a major change",
    "What does teamwork mean to you?",
    "Tell me about a time you solved a problem creatively",
    "How do you handle failure?",
    "Tell me about a leadership experience you are proud of",
    "Describe a time you had to make a difficult decision",
    "How do you handle working with difficult people?",
    "Tell me about a time you had to give someone bad news",
    "Describe a situation where you had to persuade others",
    "How do you handle ambiguity and uncertainty?",
    "Tell me about a time you had to learn something quickly",
    "Describe your approach to problem-solving",
    "How do you handle multiple competing priorities?",
    "Tell me about a time you made a mistake at work",
    "Describe a time you had to work with a team you didn't choose",
    "How do you handle feedback from peers?",
    "Tell me about a time you exceeded expectations",
    "Describe a time you had to deal with an upset customer or colleague",
    "How do you stay organized and manage your time?",
    "Tell me about a time you had to compromise",
    "Describe a situation where you had to think on your feet",
    "How do you handle work-life balance?",
    "Tell me about a time you helped a colleague succeed",
]

HR_SITUATIONAL = [
    "What would you do if you disagreed with your manager's decision?",
    "How would you handle a situation where a team member is not contributing?",
    "What would you do if you were given a task with an impossible deadline?",
    "How would you handle a situation where you made a mistake that affected the team?",
    "What would you do if you saw a colleague violating company policy?",
    "How would you handle a situation where you have too many tasks and not enough time?",
    "What would you do if a client was unhappy with your work?",
    "How would you handle a situation where you had to work with someone you don't get along with?",
    "What would you do if you were asked to do something outside your job description?",
    "How would you handle a situation where your team is falling behind on a project?",
    "What would you do if you received an offer from another company during your probation?",
    "How would you handle a situation where you had to deliver bad news to a client?",
    "What would you do if you were assigned a project you have no experience with?",
    "How would you handle a situation where two team members are in conflict?",
    "What would you do if you realized you couldn't meet a commitment you made?",
    "How would you handle a situation where you had to choose between quality and speed?",
    "What would you do if you found a more efficient way to do something but your manager resisted the change?",
    "How would you handle a situation where you had to work overtime for an extended period?",
    "What would you do if you were asked to keep a secret from your team?",
    "How would you handle a situation where you had to work with a difficult stakeholder?",
    "What would you do if you were promoted and had to manage former peers?",
    "How would you handle a situation where you had to make a decision with incomplete information?",
    "What would you do if you were asked to relocate for a project?",
    "How would you handle a situation where a project you worked on was cancelled?",
    "What would you do if you had a brilliant idea but your team was skeptical?",
    "How would you handle a situation where you had to work with outdated tools or technology?",
    "What would you do if you were asked to mentor a new hire?",
    "How would you handle a situation where you had to manage a project with no clear requirements?",
    "What would you do if you were asked to work on a project that conflicts with your values?",
    "How would you handle a situation where you had to deliver a project with limited resources?",
]

HR_MOTIVATIONAL = [
    "What motivates you to do your best work?",
    "Why are you looking for a new opportunity?",
    "What are you looking for in your next role?",
    "How does this role align with your career goals?",
    "What is your greatest professional achievement?",
    "What is your biggest professional disappointment and what did you learn?",
    "What are you passionate about outside of work?",
    "How do you stay current with industry trends?",
    "What is the one thing you would bring to our team?",
    "What does success look like to you?",
    "How do you define excellence in your work?",
    "What is the most important lesson you have learned in your career?",
    "What would your dream job look like?",
    "How do you handle self-doubt?",
    "What is the best career advice you have ever received?",
    "How do you keep yourself motivated during repetitive tasks?",
    "What is the most rewarding project you have worked on?",
    "How do you approach continuous learning?",
    "What is the most important quality for success in this role?",
    "How do you handle career setbacks?",
    "What does work-life balance mean to you?",
    "How do you handle the pressure of high expectations?",
    "What is the most challenging thing you have ever done?",
    "How do you stay focused and productive?",
    "What is the biggest risk you have taken in your career?",
    "How do you handle working in a fast-paced environment?",
    "What is the most important skill you have developed?",
    "How do you approach building relationships at work?",
    "What is the most valuable thing you have learned from a failure?",
    "How do you handle the transition between projects?",
]


def build_hr_questions_docs():
    """hr_questions collection ke liye documents banao."""
    docs = []
    for q in HR_BEHAVIORAL:
        docs.append({
            "question": q,
            "category": "behavioral",
            "asked_count": 0,
            "avg_score": 0.0,
            "total_score_sum": 0.0,
            "times_scored": 0,
        })
    for q in HR_SITUATIONAL:
        docs.append({
            "question": q,
            "category": "situational",
            "asked_count": 0,
            "avg_score": 0.0,
            "total_score_sum": 0.0,
            "times_scored": 0,
        })
    for q in HR_MOTIVATIONAL:
        docs.append({
            "question": q,
            "category": "motivational",
            "asked_count": 0,
            "avg_score": 0.0,
            "total_score_sum": 0.0,
            "times_scored": 0,
        })
    return docs


# ══════════════════════════════════════════════════════════════
# MAIN: Seed MongoDB
# ══════════════════════════════════════════════════════════════

def seed():
    print("=" * 60)
    print("MockMind Fallback Question Bank Seeder")
    print("=" * 60)

    # 1. question_bank (technical questions)
    tech_docs = build_question_bank_docs()
    question_bank_col.delete_many({})
    if tech_docs:
        question_bank_col.insert_many(tech_docs)
    print(f"  [OK] question_bank:  {len(tech_docs)} technical questions seeded")

    # 2. coding_problems
    coding_docs = build_coding_problems_docs()
    coding_problems_col.delete_many({})
    if coding_docs:
        coding_problems_col.insert_many(coding_docs)
    print(f"  [OK] coding_problems: {len(coding_docs)} coding problems seeded")

    # 3. hr_questions
    hr_docs = build_hr_questions_docs()
    hr_questions_col.delete_many({})
    if hr_docs:
        hr_questions_col.insert_many(hr_docs)
    print(f"  [OK] hr_questions:   {len(hr_docs)} HR questions seeded")

    # Summary
    total = len(tech_docs) + len(coding_docs) + len(hr_docs)
    print("=" * 60)
    print(f"  TOTAL: {total} questions/problems seeded into MongoDB")
    print(f"  - Technical Questions: {len(tech_docs)}")
    print(f"  - Coding Problems:     {len(coding_docs)}")
    print(f"  - HR Questions:        {len(hr_docs)}")
    print("=" * 60)


if __name__ == "__main__":
    seed()
